---
- hosts: all

  become: yes

  gather_facts: no

  pre_tasks:

  - name: 'install python'

    raw: 'sudo yum -y install python'
 
  roles:
    - role: lean_delivery.zabbix_agent
      zabbix_agent_server: "test.zabbix.com"
      zabbix_agent_serveractive: "test.zabbix.com"
      zabbix_agent_hostmetadata: "test metadata"
   
       

