---
- hosts: all

  become: yes

  gather_facts: no

  pre_tasks:

  - name: 'install python'

    raw: 'sudo yum -y install python'
 
- hosts: all 
  ansible_python_interpreter: /usr/bin/python3
  roles:
     - role: lean_delivery.zabbix_agent
       agent_server: 192.168.50.29
       agent_serveractive: 192.168.50.29
       zabbix_url: zabbixserver.luxfacta.com.br
       zabbix_api_use: true
       zabbix_api_user: gcordeiro
       zabbix_api_pass: Reds1959
       zabbix_create_host: present
       zabbix_host_groups:
         - Linux servers
       zabbix_link_templates:
         - Template OS Linux
       zabbix_macros:
         - macro_key: apache_type
           macro_value: reverse_proxy
   
       

