---
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
 - name: Install Python
      raw: yum -y install python
      when: check_python.rc != 0
 
 - roles:
      role: lean_delivery.zabbix_agent
      zabbix_agent_server: 192.168.50.29
      zabbix_agent_serveractive: 192.168.50.29
      zabbix_url: zabbixserver.luxfacta.com.br
       
   
       

