---
- hosts: all

  become: yes

  gather_facts: no

  pre_tasks:

  - name: 'install python'

    raw: 'sudo yum -y install python'
 
- hosts: all
  roles:
     - role: dj-wasabi.zabbix-agent
       zabbix_agent_server: zabbixserver.luxfacta.com.br
       zabbix_agent_serveractive: 192.168.50.29
       zabbix_agent_version: 3.4
       zabbix_url: zabbixserver.luxfacta.com.br
       zabbix_api_http_user: ansible
       zabbix_api_http_password: tricolor
       zabbix_api_create_hosts: True
       zabbix_api_user: ansible
       zabbix_api_pass: tricolor
       zabbix_create_host: True
       zabbix_link_templates: Template OS Linux
   
       

