---
# Playbook para instalar o zabbix-agent em hosts Linux

- name:  Install Zabbix Agent
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Zabbix Agent
      win_chocolatey:
        name: zabbix-agent
        state: started

- name: adicionado nome do host
  action: raw sed -i "s/Hostname=zabbixserver.luxfacta.com.br"{{ hname.stdout }}"/g" /etc/zabbix/zabbix_agentd.conf



